### ISSUE TITLE
Falsche Sachen rausfiltern

### ISSUE THREAD

**Issue by jdettelbach** [heavenduck/is_drug_disease#5]
Aktuell falsch positiv entdeckt:
-Monate(M)
-"dd/mm/yyyy" Daten(M)
-Kyoto(M)
-coronaviridae(M)
-Latinx(M)
-death(K)
-puberty(K)
-clay(K)
-sexual behavior(K)
-increase in mood(K)
-US-born (K) :D

**Comment by heavenduck** [comment]
von Paul erledigt
